// Mock product data with realistic names and details
export const mockProducts = [
  {
    id: "game-1",
    title: "Elden Ring",
    description:
      "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    image: "/images/elden.png",
    price: 59.99,
    discount: 25,
    platform: "Steam",
    category: "games",
    publisher: "Bandai Namco",
    releaseDate: "2022-02-25",
    genres: ["Action", "RPG", "Open World"],
    rating: 4.8,
    sales: 12000000,
    features: ["Open World", "Multiplayer", "Controller Support"],
    images: [
      "/images/elden.png",
      "/images/elden-desc1.png",
      "/images/elden-desc2.png",
      "/images/elden-desc3.png",
      "/images/elden-desc4.png",
    ],
  },
  {
    id: "game-2",
    title: "Cyberpunk 2077",
    description:
      "An open-world, action-adventure RPG set in Night City, a megalopolis obsessed with power, glamour and body modification.",
    image: "/images/cyberpunk.png",
    price: 59.99,
    discount: 50,
    platform: "GOG",
    category: "games",
    publisher: "CD Projekt RED",
    releaseDate: "2020-12-10",
    genres: ["RPG", "Open World", "Sci-Fi"],
    rating: 3.9,
    sales: 18000000,
    features: ["Open World", "Single-player", "Story Rich"],
    images: [
      "/images/cyberpunk.png",
      "/images/cyberpunk-desc1.jpg",
      "/images/cyberpunk-desc2.jpg",
      "/images/cyberpunk-desc3.jpg",
      "/images/cyberpunk-desc4.jpg",
    ],
  },
  {
    id: "game-3",
    title: "Red Dead Redemption 2",
    description:
      "An epic tale of life in America's unforgiving heartland. The game's vast and atmospheric world also provides the foundation for a brand new online multiplayer experience.",
    image: "/images/rdr2.jpg",
    price: 59.99,
    discount: 40,
    platform: "Epic Games",
    category: "games",
    publisher: "Rockstar Games",
    releaseDate: "2019-11-05",
    genres: ["Action", "Adventure", "Open World"],
    rating: 4.9,
    sales: 45000000,
    features: ["Open World", "Multiplayer", "Story Rich"],
    images: [
      "/images/rdr2.jpg",
      "/images/rdr2-desc1.jpg",
      "/images/rdr2-desc2.jpg",
      "/images/rdr2-desc3.jpg",
      "/images/rdr2-desc4.jpg",
    ],
  },
  {
    id: "game-4",
    title: "FIFA 23",
    description: "Experience the world's game with over 19,000 players, 700+ teams, 100+ stadiums, and 30+ leagues.",
    image: "/images/fifa23.jpg",
    price: 69.99,
    discount: 35,
    platform: "Origin",
    category: "games",
    publisher: "Electronic Arts",
    releaseDate: "2022-09-30",
    genres: ["Sports", "Simulation"],
    rating: 4.2,
    sales: 10000000,
    features: ["Multiplayer", "Controller Support", "Online Competitive"],
    images: [
      "/images/fifa23.jpg",
      "/images/fifa23-desc1.jpg",
      "/images/fifa23-desc2.jpg",
      "/images/fifa23-desc3.jpg",
      "/images/fifa23-desc4.jpg",
    ],
  },
  {
    id: "game-5",
    title: "The Witcher 3: Wild Hunt",
    description: "A story-driven, open world adventure set in a dark fantasy universe.",
    image: "/images/witcher3.jpg",
    price: 39.99,
    discount: 70,
    platform: "Steam",
    category: "games",
    publisher: "CD Projekt RED",
    releaseDate: "2015-05-19",
    genres: ["RPG", "Open World", "Fantasy"],
    rating: 4.9,
    sales: 40000000,
    features: ["Open World", "Story Rich", "Atmospheric"],
    images: [
      "/images/witcher3.jpg",
      "/images/witcher3-desc1.jpg",
      "/images/witcher3-desc2.jpg",
      "/images/witcher3-desc3.jpg",
      "/images/witcher3-desc4.jpg",
    ],
  },
  {
    id: "game-6",
    title: "Battlefield 2042",
    description: "A first-person shooter that marks the return to the iconic all-out warfare of the franchise.",
    image: "/images/battlefield2042.jpg",
    price: 59.99,
    discount: 60,
    platform: "Origin",
    category: "games",
    publisher: "Electronic Arts",
    releaseDate: "2021-11-19",
    genres: ["FPS", "Action", "Multiplayer"],
    rating: 3.2,
    sales: 4500000,
    features: ["Multiplayer", "FPS", "Action"],
    images: [
      "/images/battlefield2042.jpg",
      "/images/battlefield2042desc1.jpeg",
      "/images/battlefielddesc2.jpeg",
      "/images/battlefielddesc3.jpeg",
      "/images/battlefielddesc4.jpeg",
    ],
  },
  {
    id: "game-7",
    title: "Hollow Knight",
    description:
      "A challenging 2D action-adventure. Explore twisting caverns, battle tainted creatures and escape intricate traps.",
    image: "/images/hollowknight.jpg",
    price: 14.99,
    discount: 50,
    platform: "Steam",
    category: "games",
    publisher: "Team Cherry",
    releaseDate: "2017-02-24",
    genres: ["Metroidvania", "Indie", "Action"],
    rating: 4.9,
    sales: 3000000,
    features: ["Atmospheric", "Difficult", "Great Soundtrack"],
    images: [
      "/images/hollowknight.jpg",
      "/images/hollowknight-desc1.jpg",
      "/images/hollowknight-desc2.jpg",
      "/images/hollowknight-desc3.jpg",
      "/images/hollowknight-desc4.jpg",
    ],
  },
  {
    id: "game-8",
    title: "Hades",
    description:
      "A god-like rogue-like dungeon crawler that combines the best aspects of Supergiant's critically acclaimed titles.",
    image: "/images/hades.jpg",
    price: 24.99,
    discount: 30,
    platform: "Epic Games",
    category: "games",
    publisher: "Supergiant Games",
    releaseDate: "2020-09-17",
    genres: ["Roguelike", "Indie", "Action"],
    rating: 4.8,
    sales: 1000000,
    features: ["Great Soundtrack", "Action Roguelike", "Story Rich"],
    images: [
      "/images/hades.jpg",
      "/images/hades-desc1.jpg",
      "/images/hades-desc2.jpg",
      "/images/hades-desc3.jpg",
      "/images/hades-desc4.jpg",
    ],
  },
  {
    id: "software-1",
    title: "Microsoft Office 2023",
    description: "The latest version of Microsoft Office with Word, Excel, PowerPoint, and more.",
    image: "/images/microsoftoffice.png",
    price: 149.99,
    discount: 20,
    platform: "Windows",
    category: "software",
    publisher: "Microsoft",
    releaseDate: "2022-10-05",
    genres: ["Productivity", "Business"],
    rating: 4.5,
    sales: 8000000,
    features: ["Word Processing", "Spreadsheets", "Presentations"],
    images: [
      "/images/microsoftoffice.png",
      "/images/microsoftoffice-desc1.jpg",
      "/images/microsoftoffice-desc2.jpg",
      "/images/microsoftoffice-desc3.jpg",
      "/images/microsoftoffice-desc4.jpg",
    ],
  },
  {
    id: "software-2",
    title: "Adobe Creative Cloud",
    description:
      "A collection of 20+ desktop and mobile apps and services for photography, design, video, web, UX, and more.",
    image: "/images/adobecreativecloud.jpg",
    price: 52.99,
    discount: 15,
    platform: "Cross-platform",
    category: "software",
    publisher: "Adobe",
    releaseDate: "2022-01-15",
    genres: ["Creative", "Design", "Photography"],
    rating: 4.7,
    sales: 5000000,
    features: ["Photoshop", "Illustrator", "Premiere Pro"],
    images: [
      "/images/adobecreativecloud.jpg",
      "/images/adobecreativecloud-desc1.jpg",
      "/images/adobecreativecloud-desc2.jpg",
      "/images/adobecreativecloud-desc3.jpg",
      "/images/adobecreativecloud-desc4.jpg",
    ],
  },
  {
    id: "software-3",
    title: "Windows 11 Pro",
    description: "The latest version of Windows with advanced security and management features.",
    image: "/images/windows11.jpg",
    price: 199.99,
    discount: 10,
    platform: "Windows",
    category: "software",
    publisher: "Microsoft",
    releaseDate: "2021-10-05",
    genres: ["Operating System", "Productivity"],
    rating: 4.3,
    sales: 20000000,
    features: ["Enhanced Security", "Virtual Desktops", "Microsoft Store"],
    images: [
      "/images/windows11.jpg",
      "/images/windows11-desc1.jpg",
      "/images/windows11-desc2.jpg",
      "/images/windows11-desc3.jpg",
      "/images/windows11-desc4.jpg",
    ],
  },
  {
    id: "software-4",
    title: "Autodesk Maya 2023",
    description: "3D animation, modeling, simulation, and rendering software for film, TV, and games.",
    image: "/placeholder.svg?height=300&width=300&text=Maya+2023",
    price: 205.0,
    discount: 25,
    platform: "Windows/Mac",
    category: "software",
    publisher: "Autodesk",
    releaseDate: "2022-03-29",
    genres: ["3D Modeling", "Animation", "Design"],
    rating: 4.6,
    sales: 1000000,
    features: ["3D Modeling", "Animation", "Visual Effects"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Maya+2023",
      "/placeholder.svg?height=300&width=300&text=Maya+2023",
      "/placeholder.svg?height=300&width=300&text=Maya+2023",
      "/placeholder.svg?height=300&width=300&text=Maya+2023",
    ],
  },
  {
    id: "software-5",
    title: "Norton 360 Deluxe",
    description: "Comprehensive protection for your devices and online privacy.",
    image: "/placeholder.svg?height=300&width=300&text=Norton+360",
    price: 89.99,
    discount: 50,
    platform: "Cross-platform",
    category: "software",
    publisher: "NortonLifeLock",
    releaseDate: "2022-05-17",
    genres: ["Security", "Antivirus"],
    rating: 4.2,
    sales: 3000000,
    features: ["Real-time Protection", "VPN", "Password Manager"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Norton+360",
      "/placeholder.svg?height=300&width=300&text=Norton+360",
      "/placeholder.svg?height=300&width=300&text=Norton+360",
      "/placeholder.svg?height=300&width=300&text=Norton+360",
    ],
  },
  {
    id: "digital-1",
    title: "Steam Wallet $50",
    description: "Add funds to your Steam Wallet to purchase games, software, and more on Steam.",
    image: "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
    price: 50.0,
    discount: 5,
    platform: "Steam",
    category: "digital",
    publisher: "Valve",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Digital Currency"],
    rating: 4.9,
    sales: 15000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
      "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
      "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
      "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
    ],
  },
  {
    id: "digital-2",
    title: "Xbox Game Pass Ultimate (3 Months)",
    description: "Get unlimited access to over 100 high-quality games on console, PC, and cloud.",
    image: "/placeholder.svg?height=300&width=300&text=Game+Pass",
    price: 44.99,
    discount: 30,
    platform: "Xbox",
    category: "digital",
    publisher: "Microsoft",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Gaming Service"],
    rating: 4.8,
    sales: 10000000,
    features: ["Xbox Live Gold", "EA Play", "Cloud Gaming"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Game+Pass",
      "/placeholder.svg?height=300&width=300&text=Game+Pass",
      "/placeholder.svg?height=300&width=300&text=Game+Pass",
      "/placeholder.svg?height=300&width=300&text=Game+Pass",
    ],
  },
  {
    id: "digital-3",
    title: "PlayStation Plus (12 Months)",
    description:
      "Enhance your PlayStation experience with online multiplayer, monthly games, exclusive discounts, and more.",
    image: "/placeholder.svg?height=300&width=300&text=PS+Plus",
    price: 59.99,
    discount: 20,
    platform: "PlayStation",
    category: "digital",
    publisher: "Sony",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Gaming Service"],
    rating: 4.7,
    sales: 9000000,
    features: ["Online Multiplayer", "Monthly Games", "Exclusive Discounts"],
    images: [
      "/placeholder.svg?height=300&width=300&text=PS+Plus",
      "/placeholder.svg?height=300&width=300&text=PS+Plus",
      "/placeholder.svg?height=300&width=300&text=PS+Plus",
      "/placeholder.svg?height=300&width=300&text=PS+Plus",
    ],
  },
  {
    id: "digital-4",
    title: "Spotify Premium (12 Months)",
    description: "Ad-free music listening, offline playback, and on-demand playback.",
    image: "/placeholder.svg?height=300&width=300&text=Spotify",
    price: 99.99,
    discount: 15,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Spotify",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Music Service"],
    rating: 4.6,
    sales: 20000000,
    features: ["Ad-free", "Offline Listening", "High Quality Audio"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Spotify",
      "/placeholder.svg?height=300&width=300&text=Spotify",
      "/placeholder.svg?height=300&width=300&text=Spotify",
      "/placeholder.svg?height=300&width=300&text=Spotify",
    ],
  },
  {
    id: "digital-5",
    title: "Netflix Gift Card $50",
    description: "Give the gift of unlimited entertainment with a Netflix gift card.",
    image: "/placeholder.svg?height=300&width=300&text=Netflix",
    price: 50.0,
    discount: 0,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Netflix",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Streaming Service"],
    rating: 4.5,
    sales: 25000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Netflix",
      "/placeholder.svg?height=300&width=300&text=Netflix",
      "/placeholder.svg?height=300&width=300&text=Netflix",
      "/placeholder.svg?height=300&width=300&text=Netflix",
    ],
  },
  {
    id: "digital-6",
    title: "Roblox Gift Card $25",
    description: "Get Robux to purchase avatars, accessories, and more in Roblox.",
    image: "/placeholder.svg?height=300&width=300&text=Roblox",
    price: 25.0,
    discount: 0,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Roblox Corporation",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Gaming Currency"],
    rating: 4.7,
    sales: 30000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Roblox",
      "/placeholder.svg?height=300&width=300&text=Roblox",
      "/placeholder.svg?height=300&width=300&text=Roblox",
      "/placeholder.svg?height=300&width=300&text=Roblox",
    ],
  },
  // New games
  {
    id: "game-11",
    title: "God of War Ragnarök",
    description: "Embark on a mythic journey for answers and allies before Ragnarök arrives.",
    image: "/placeholder.svg?height=300&width=300&text=God+of+War",
    price: 69.99,
    discount: 15,
    platform: "PlayStation",
    category: "games",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2022-11-09",
    genres: ["Action", "Adventure"],
    rating: 4.9,
    sales: 5200000,
    features: ["Story Rich", "Action", "Single-player"],
    images: [
      "/placeholder.svg?height=300&width=300&text=God+of+War",
      "/placeholder.svg?height=300&width=300&text=God+of+War",
      "/placeholder.svg?height=300&width=300&text=God+of+War",
      "/placeholder.svg?height=300&width=300&text=God+of+War",
    ],
  },
  {
    id: "game-12",
    title: "Horizon Forbidden West",
    description: "Join Aloy as she braves the Forbidden West, a deadly frontier that conceals mysterious new threats.",
    image: "/placeholder.svg?height=300&width=300&text=Horizon",
    price: 59.99,
    discount: 25,
    platform: "PlayStation",
    category: "games",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2022-02-18",
    genres: ["Action", "RPG", "Open World"],
    rating: 4.7,
    sales: 8300000,
    features: ["Open World", "Female Protagonist", "Story Rich"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Horizon",
      "/placeholder.svg?height=300&width=300&text=Horizon",
      "/placeholder.svg?height=300&width=300&text=Horizon",
      "/placeholder.svg?height=300&width=300&text=Horizon",
    ],
  },
  {
    id: "game-13",
    title: "Forza Horizon 5",
    description: "Your Ultimate Horizon Adventure awaits! Explore the vibrant open world landscapes of Mexico.",
    image: "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
    price: 59.99,
    discount: 30,
    platform: "Xbox/PC",
    category: "games",
    publisher: "Xbox Game Studios",
    releaseDate: "2021-11-09",
    genres: ["Racing", "Open World"],
    rating: 4.8,
    sales: 10000000,
    features: ["Open World", "Multiplayer", "Realistic"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
      "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
      "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
      "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
    ],
  },
  {
    id: "game-14",
    title: "Resident Evil Village",
    description:
      "Experience survival horror like never before in the 8th major installment in the Resident Evil franchise.",
    image: "/capcomlogo.png",
    price: 49.99,
    discount: 40,
    platform: "Multiple",
    category: "games",
    publisher: "Capcom",
    releaseDate: "2021-05-07",
    genres: ["Horror", "Survival", "First-Person"],
    rating: 4.6,
    sales: 6500000,
    features: ["Horror", "First-Person", "Story Rich"],
    images: ["/capcomlogo.png", "/capcomlogo.png", "/capcomlogo.png", "/capcomlogo.png"],
  },
  {
    id: "game-15",
    title: "Final Fantasy XVI",
    description: "The latest installment in the legendary RPG series, featuring a dark fantasy setting.",
    image: "/placeholder.svg?height=300&width=300&text=FF+XVI",
    price: 69.99,
    discount: 0,
    platform: "PlayStation",
    category: "games",
    publisher: "Square Enix",
    releaseDate: "2023-06-22",
    genres: ["RPG", "Action", "Fantasy"],
    rating: 4.7,
    sales: 3000000,
    features: ["Story Rich", "Fantasy", "Action Combat"],
    images: [
      "/placeholder.svg?height=300&width=300&text=FF+XVI",
      "/placeholder.svg?height=300&width=300&text=FF+XVI",
      "/placeholder.svg?height=300&width=300&text=FF+XVI",
      "/placeholder.svg?height=300&width=300&text=FF+XVI",
    ],
  },
  // New software
  {
    id: "software-7",
    title: "Affinity Designer 2",
    description: "Professional graphic design software with no subscription.",
    image: "/affinitydesigner2.jpg",
    price: 69.99,
    discount: 20,
    platform: "Cross-platform",
    category: "software",
    publisher: "Serif",
    releaseDate: "2022-11-09",
    genres: ["Design", "Vector Graphics"],
    rating: 4.8,
    sales: 1500000,
    features: ["Vector Design", "No Subscription", "Professional Tools"],
    images: ["/affinitydesigner2.jpg", "/affinitydesigner2.jpg", "/affinitydesigner2.jpg", "/affinitydesigner2.jpg"],
  },
  {
    id: "software-8",
    title: "DaVinci Resolve Studio",
    description: "Professional video editing, color correction, visual effects, and audio post-production.",
    image: "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
    price: 295.0,
    discount: 0,
    platform: "Cross-platform",
    category: "software",
    publisher: "Blackmagic Design",
    releaseDate: "2022-08-23",
    genres: ["Video Editing", "Color Grading"],
    rating: 4.9,
    sales: 2000000,
    features: ["8K Support", "Color Grading", "Audio Post"],
    images: [
      "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
      "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
      "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
      "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
    ],
  },
  // New digital products
  {
    id: "digital-7",
    title: "Disney+ (12 Months)",
    description: "Stream exclusive Disney originals, movies, shows, and more.",
    image: "/placeholder.svg?height=300&width=300&text=Disney+",
    price: 79.99,
    discount: 15,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Disney",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Streaming Service"],
    rating: 4.6,
    sales: 15000000,
    features: ["4K Streaming", "Family Content", "Original Shows"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Disney+",
      "/placeholder.svg?height=300&width=300&text=Disney+",
      "/placeholder.svg?height=300&width=300&text=Disney+",
      "/placeholder.svg?height=300&width=300&text=Disney+",
    ],
  },
  {
    id: "digital-8",
    title: "Amazon Gift Card $100",
    description: "Shop millions of products on Amazon with this gift card.",
    image: "/amazon100.png",
    price: 100.0,
    discount: 0,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Amazon",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Shopping"],
    rating: 4.9,
    sales: 50000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
    images: ["/amazon100.png", "/amazon100.png", "/amazon100.png", "/amazon100.png"],
  },
  // Adding more products to test pagination (at least 60 total products)
  {
    id: "game-16",
    title: "Assassin's Creed Valhalla",
    description: "Become a legendary Viking warrior raised on tales of battle and glory.",
    image: "/placeholder.svg?height=300&width=300&text=AC+Valhalla",
    price: 59.99,
    discount: 40,
    platform: "Multiple",
    category: "games",
    publisher: "Ubisoft",
    releaseDate: "2020-11-10",
    genres: ["Action", "RPG", "Open World"],
    rating: 4.5,
    sales: 7000000,
    features: ["Open World", "Historical", "RPG Elements"],
    images: [
      "/placeholder.svg?height=300&width=300&text=AC+Valhalla",
      "/placeholder.svg?height=300&width=300&text=AC+Valhalla",
      "/placeholder.svg?height=300&width=300&text=AC+Valhalla",
      "/placeholder.svg?height=300&width=300&text=AC+Valhalla",
    ],
  },
  {
    id: "game-17",
    title: "Call of Duty: Modern Warfare II",
    description:
      "The sequel to 2019's blockbuster Modern Warfare, featuring a new campaign and multiplayer experience.",
    image: "/placeholder.svg?height=300&width=300&text=COD+MW2",
    price: 69.99,
    discount: 20,
    platform: "Multiple",
    category: "games",
    publisher: "Activision",
    releaseDate: "2022-10-28",
    genres: ["FPS", "Action", "Multiplayer"],
    rating: 4.3,
    sales: 15000000,
    features: ["Multiplayer", "Campaign", "Co-op"],
    images: [
      "/placeholder.svg?height=300&width=300&text=COD+MW2",
      "/placeholder.svg?height=300&width=300&text=COD+MW2",
      "/placeholder.svg?height=300&width=300&text=COD+MW2",
      "/placeholder.svg?height=300&width=300&text=COD+MW2",
    ],
  },
  {
    id: "game-18",
    title: "Minecraft",
    description: "A sandbox game that allows players to build and explore virtual worlds made up of blocks.",
    image: "/placeholder.svg?height=300&width=300&text=Minecraft",
    price: 29.99,
    discount: 0,
    platform: "Multiple",
    category: "games",
    publisher: "Mojang Studios",
    releaseDate: "2011-11-18",
    genres: ["Sandbox", "Survival", "Adventure"],
    rating: 4.8,
    sales: 238000000,
    features: ["Building", "Multiplayer", "Modding"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Minecraft",
      "/placeholder.svg?height=300&width=300&text=Minecraft",
      "/placeholder.svg?height=300&width=300&text=Minecraft",
      "/placeholder.svg?height=300&width=300&text=Minecraft",
    ],
  },
  {
    id: "game-19",
    title: "Grand Theft Auto V",
    description: "An action-adventure game set in the fictional state of San Andreas.",
    image: "/placeholder.svg?height=300&width=300&text=GTA+V",
    price: 29.99,
    discount: 50,
    platform: "Multiple",
    category: "games",
    publisher: "Rockstar Games",
    releaseDate: "2013-09-17",
    genres: ["Action", "Adventure", "Open World"],
    rating: 4.8,
    sales: 170000000,
    features: ["Open World", "Multiplayer", "Story Rich"],
    images: [
      "/placeholder.svg?height=300&width=300&text=GTA+V",
      "/placeholder.svg?height=300&width=300&text=GTA+V",
      "/placeholder.svg?height=300&width=300&text=GTA+V",
      "/placeholder.svg?height=300&width=300&text=GTA+V",
    ],
  },
  {
    id: "game-20",
    title: "The Last of Us Part II",
    description: "A story of revenge set in a post-apocalyptic United States.",
    image: "/placeholder.svg?height=300&width=300&text=TLOU2",
    price: 59.99,
    discount: 30,
    platform: "PlayStation",
    category: "games",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2020-06-19",
    genres: ["Action", "Adventure", "Survival"],
    rating: 4.6,
    sales: 10000000,
    features: ["Story Rich", "Action", "Emotional"],
    images: [
      "/placeholder.svg?height=300&width=300&text=TLOU2",
      "/placeholder.svg?height=300&width=300&text=TLOU2",
      "/placeholder.svg?height=300&width=300&text=TLOU2",
      "/placeholder.svg?height=300&width=300&text=TLOU2",
    ],
  },
  {
    id: "game-21",
    title: "Stardew Valley",
    description: "A farming simulation game where you build and manage your own farm.",
    image: "/placeholder.svg?height=300&width=300&text=Stardew+Valley",
    price: 14.99,
    discount: 25,
    platform: "Multiple",
    category: "games",
    publisher: "ConcernedApe",
    releaseDate: "2016-02-26",
    genres: ["Simulation", "RPG", "Indie"],
    rating: 4.9,
    sales: 20000000,
    features: ["Farming", "Life Sim", "Pixel Graphics"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Stardew+Valley",
      "/placeholder.svg?height=300&width=300&text=Stardew+Valley",
      "/placeholder.svg?height=300&width=300&text=Stardew+Valley",
      "/placeholder.svg?height=300&width=300&text=Stardew+Valley",
    ],
  },
  {
    id: "game-22",
    title: "Among Us",
    description: "A party game of teamwork and betrayal for 4-15 players in space.",
    image: "/placeholder.svg?height=300&width=300&text=Among+Us",
    price: 4.99,
    discount: 0,
    platform: "Multiple",
    category: "games",
    publisher: "Innersloth",
    releaseDate: "2018-06-15",
    genres: ["Party", "Social Deduction", "Multiplayer"],
    rating: 4.5,
    sales: 15000000,
    features: ["Online Co-Op", "Cross-Platform", "Social Deduction"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Among+Us",
      "/placeholder.svg?height=300&width=300&text=Among+Us",
      "/placeholder.svg?height=300&width=300&text=Among+Us",
      "/placeholder.svg?height=300&width=300&text=Among+Us",
    ],
  },
  {
    id: "game-23",
    title: "Valorant",
    description: "A 5v5 character-based tactical FPS where precise gunplay meets unique agent abilities.",
    image: "/placeholder.svg?height=300&width=300&text=Valorant",
    price: 0,
    discount: 0,
    platform: "PC",
    category: "games",
    publisher: "Riot Games",
    releaseDate: "2020-06-02",
    genres: ["FPS", "Tactical", "Competitive"],
    rating: 4.4,
    sales: 0,
    features: ["Free to Play", "Competitive", "Team-Based"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Valorant",
      "/placeholder.svg?height=300&width=300&text=Valorant",
      "/placeholder.svg?height=300&width=300&text=Valorant",
      "/placeholder.svg?height=300&width=300&text=Valorant",
    ],
  },
  {
    id: "game-24",
    title: "Sekiro: Shadows Die Twice",
    description: "An action-adventure game set in a reimagined late 16th century Japan.",
    image: "/placeholder.svg?height=300&width=300&text=Sekiro",
    price: 59.99,
    discount: 35,
    platform: "Multiple",
    category: "games",
    publisher: "Activision",
    releaseDate: "2019-03-22",
    genres: ["Action", "Adventure", "Souls-like"],
    rating: 4.8,
    sales: 5000000,
    features: ["Challenging", "Single-player", "Story Rich"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Sekiro",
      "/placeholder.svg?height=300&width=300&text=Sekiro",
      "/placeholder.svg?height=300&width=300&text=Sekiro",
      "/placeholder.svg?height=300&width=300&text=Sekiro",
    ],
  },
  {
    id: "game-25",
    title: "Death Stranding",
    description: "An action game set in an apocalyptic United States, where you play as a courier delivering packages.",
    image: "/placeholder.svg?height=300&width=300&text=Death+Stranding",
    price: 39.99,
    discount: 50,
    platform: "Multiple",
    category: "games",
    publisher: "505 Games",
    releaseDate: "2019-11-08",
    genres: ["Action", "Adventure", "Open World"],
    rating: 4.4,
    sales: 5000000,
    features: ["Story Rich", "Open World", "Atmospheric"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Death+Stranding",
      "/placeholder.svg?height=300&width=300&text=Death+Stranding",
      "/placeholder.svg?height=300&width=300&text=Death+Stranding",
      "/placeholder.svg?height=300&width=300&text=Death+Stranding",
    ],
  },
  {
    id: "software-9",
    title: "Ableton Live 11",
    description: "Professional music production software for composing, recording, mixing, and mastering.",
    image: "/placeholder.svg?height=300&width=300&text=Ableton+Live",
    price: 449.0,
    discount: 10,
    platform: "Windows/Mac",
    category: "software",
    publisher: "Ableton",
    releaseDate: "2021-02-23",
    genres: ["Music Production", "Audio"],
    rating: 4.8,
    sales: 1000000,
    features: ["Audio Production", "MIDI", "VST Support"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Ableton+Live",
      "/placeholder.svg?height=300&width=300&text=Ableton+Live",
      "/placeholder.svg?height=300&width=300&text=Ableton+Live",
      "/placeholder.svg?height=300&width=300&text=Ableton+Live",
    ],
  },
  {
    id: "software-10",
    title: "Final Cut Pro",
    description: "Professional video editing software designed for macOS.",
    image: "/placeholder.svg?height=300&width=300&text=Final+Cut+Pro",
    price: 299.99,
    discount: 0,
    platform: "Mac",
    category: "software",
    publisher: "Apple",
    releaseDate: "2022-10-27",
    genres: ["Video Editing", "Professional"],
    rating: 4.7,
    sales: 2000000,
    features: ["4K Support", "Motion Graphics", "Color Grading"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Final+Cut+Pro",
      "/placeholder.svg?height=300&width=300&text=Final+Cut+Pro",
      "/placeholder.svg?height=300&width=300&text=Final+Cut+Pro",
      "/placeholder.svg?height=300&width=300&text=Final+Cut+Pro",
    ],
  },
  {
    id: "software-11",
    title: "Sketch",
    description: "Vector graphics editor for macOS used primarily for user interface and user experience design.",
    image: "/placeholder.svg?height=300&width=300&text=Sketch",
    price: 99.0,
    discount: 20,
    platform: "Mac",
    category: "software",
    publisher: "Sketch B.V.",
    releaseDate: "2022-05-15",
    genres: ["Design", "UI/UX"],
    rating: 4.6,
    sales: 1500000,
    features: ["Vector Editing", "Prototyping", "Collaboration"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Sketch",
      "/placeholder.svg?height=300&width=300&text=Sketch",
      "/placeholder.svg?height=300&width=300&text=Sketch",
      "/placeholder.svg?height=300&width=300&text=Sketch",
    ],
  },
  {
    id: "software-12",
    title: "Unity Pro",
    description: "A powerful development platform for creating 2D and 3D games and interactive experiences.",
    image: "/placeholder.svg?height=300&width=300&text=Unity+Pro",
    price: 1800.0,
    discount: 15,
    platform: "Cross-platform",
    category: "software",
    publisher: "Unity Technologies",
    releaseDate: "2022-11-01",
    genres: ["Game Development", "3D"],
    rating: 4.5,
    sales: 1000000,
    features: ["Real-time Development", "Cross-platform", "Asset Store"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Unity+Pro",
      "/placeholder.svg?height=300&width=300&text=Unity+Pro",
      "/placeholder.svg?height=300&width=300&text=Unity+Pro",
      "/placeholder.svg?height=300&width=300&text=Unity+Pro",
    ],
  },
  {
    id: "software-13",
    title: "Parallels Desktop",
    description: "Run Windows applications on your Mac without rebooting.",
    image: "/placeholder.svg?height=300&width=300&text=Parallels",
    price: 79.99,
    discount: 20,
    platform: "Mac",
    category: "software",
    publisher: "Parallels International GmbH",
    releaseDate: "2022-08-09",
    genres: ["Virtualization", "Productivity"],
    rating: 4.5,
    sales: 3000000,
    features: ["Windows on Mac", "Seamless Integration", "Performance Optimization"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Parallels",
      "/placeholder.svg?height=300&width=300&text=Parallels",
      "/placeholder.svg?height=300&width=300&text=Parallels",
      "/placeholder.svg?height=300&width=300&text=Parallels",
    ],
  },
  {
    id: "digital-9",
    title: "Apple Gift Card $50",
    description: "Use for apps, games, music, movies, TV shows, iCloud, and more.",
    image: "/placeholder.svg?height=300&width=300&text=Apple+Gift+Card",
    price: 50.0,
    discount: 0,
    platform: "Apple",
    category: "digital",
    publisher: "Apple",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Digital"],
    rating: 4.9,
    sales: 40000000,
    features: ["Instant Delivery", "No Expiration", "Multiple Uses"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Apple+Gift+Card",
      "/placeholder.svg?height=300&width=300&text=Apple+Gift+Card",
      "/placeholder.svg?height=300&width=300&text=Apple+Gift+Card",
      "/placeholder.svg?height=300&width=300&text=Apple+Gift+Card",
    ],
  },
  {
    id: "digital-10",
    title: "YouTube Premium (12 Months)",
    description: "Ad-free videos, background play, and YouTube Music Premium.",
    image: "/placeholder.svg?height=300&width=300&text=YouTube+Premium",
    price: 119.99,
    discount: 10,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Google",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Streaming Service"],
    rating: 4.5,
    sales: 10000000,
    features: ["Ad-free", "Background Play", "Downloads"],
    images: [
      "/placeholder.svg?height=300&width=300&text=YouTube+Premium",
      "/placeholder.svg?height=300&width=300&text=YouTube+Premium",
      "/placeholder.svg?height=300&width=300&text=YouTube+Premium",
      "/placeholder.svg?height=300&width=300&text=YouTube+Premium",
    ],
  },
  {
    id: "digital-11",
    title: "Nintendo eShop Card $50",
    description: "Add funds to your Nintendo eShop account to purchase games and DLC.",
    image: "/placeholder.svg?height=300&width=300&text=Nintendo+eShop",
    price: 50.0,
    discount: 0,
    platform: "Nintendo",
    category: "digital",
    publisher: "Nintendo",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Gaming"],
    rating: 4.8,
    sales: 20000000,
    features: ["Instant Delivery", "No Expiration", "Switch Compatible"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Nintendo+eShop",
      "/placeholder.svg?height=300&width=300&text=Nintendo+eShop",
      "/placeholder.svg?height=300&width=300&text=Nintendo+eShop",
      "/placeholder.svg?height=300&width=300&text=Nintendo+eShop",
    ],
  },
  {
    id: "digital-12",
    title: "Audible Membership (6 Months)",
    description: "Access to thousands of audiobooks and podcasts.",
    image: "/placeholder.svg?height=300&width=300&text=Audible",
    price: 89.94,
    discount: 25,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Amazon",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Audiobooks"],
    rating: 4.7,
    sales: 8000000,
    features: ["Monthly Credits", "Exclusive Content", "Offline Listening"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Audible",
      "/placeholder.svg?height=300&width=300&text=Audible",
      "/placeholder.svg?height=300&width=300&text=Audible",
      "/placeholder.svg?height=300&width=300&text=Audible",
    ],
  },
  {
    id: "game-26",
    title: "Diablo IV",
    description: "The newest installment in the Diablo series, featuring a dark, gothic world.",
    image: "/placeholder.svg?height=300&width=300&text=Diablo+IV",
    price: 69.99,
    discount: 0,
    platform: "Multiple",
    category: "games",
    publisher: "Blizzard Entertainment",
    releaseDate: "2023-06-06",
    genres: ["Action RPG", "Hack and Slash", "Multiplayer"],
    rating: 4.5,
    sales: 10000000,
    features: ["Open World", "Multiplayer", "Character Classes"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Diablo+IV",
      "/placeholder.svg?height=300&width=300&text=Diablo+IV",
      "/placeholder.svg?height=300&width=300&text=Diablo+IV",
      "/placeholder.svg?height=300&width=300&text=Diablo+IV",
    ],
  },
  {
    id: "game-27",
    title: "Hogwarts Legacy",
    description: "An immersive, open-world action RPG set in the world of Harry Potter.",
    image: "/placeholder.svg?height=300&width=300&text=Hogwarts+Legacy",
    price: 59.99,
    discount: 15,
    platform: "Multiple",
    category: "games",
    publisher: "Warner Bros. Games",
    releaseDate: "2023-02-10",
    genres: ["RPG", "Open World", "Fantasy"],
    rating: 4.6,
    sales: 12000000,
    features: ["Open World", "Magic", "Story Rich"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Hogwarts+Legacy",
      "/placeholder.svg?height=300&width=300&text=Hogwarts+Legacy",
      "/placeholder.svg?height=300&width=300&text=Hogwarts+Legacy",
      "/placeholder.svg?height=300&width=300&text=Hogwarts+Legacy",
    ],
  },
  {
    id: "game-28",
    title: "Starfield",
    description: "A next-generation role-playing game set amongst the stars.",
    image: "/placeholder.svg?height=300&width=300&text=Starfield",
    price: 69.99,
    discount: 0,
    platform: "Xbox/PC",
    category: "games",
    publisher: "Bethesda Softworks",
    releaseDate: "2023-09-06",
    genres: ["RPG", "Open World", "Sci-Fi"],
    rating: 4.4,
    sales: 8000000,
    features: ["Open World", "Space Exploration", "Character Customization"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Starfield",
      "/placeholder.svg?height=300&width=300&text=Starfield",
      "/placeholder.svg?height=300&width=300&text=Starfield",
      "/placeholder.svg?height=300&width=300&text=Starfield",
    ],
  },
  {
    id: "game-29",
    title: "Baldur's Gate 3",
    description: "A party-based RPG set in the Dungeons & Dragons universe.",
    image: "/placeholder.svg?height=300&width=300&text=Baldurs+Gate+3",
    price: 59.99,
    discount: 0,
    platform: "PC",
    category: "games",
    publisher: "Larian Studios",
    releaseDate: "2023-08-03",
    genres: ["RPG", "Turn-Based", "Fantasy"],
    rating: 4.9,
    sales: 5000000,
    features: ["Turn-Based Combat", "Character Customization", "Multiplayer"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Baldurs+Gate+3",
      "/placeholder.svg?height=300&width=300&text=Baldurs+Gate+3",
      "/placeholder.svg?height=300&width=300&text=Baldurs+Gate+3",
      "/placeholder.svg?height=300&width=300&text=Baldurs+Gate+3",
    ],
  },
  {
    id: "game-30",
    title: "The Legend of Zelda: Tears of the Kingdom",
    description: "The sequel to Breath of the Wild, featuring a vast open world and new abilities.",
    image: "/placeholder.svg?height=300&width=300&text=Zelda+TOTK",
    price: 69.99,
    discount: 10,
    platform: "Nintendo Switch",
    category: "games",
    publisher: "Nintendo",
    releaseDate: "2023-05-12",
    genres: ["Action", "Adventure", "Open World"],
    rating: 4.9,
    sales: 15000000,
    features: ["Open World", "Puzzle Solving", "Exploration"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Zelda+TOTK",
      "/placeholder.svg?height=300&width=300&text=Zelda+TOTK",
      "/placeholder.svg?height=300&width=300&text=Zelda+TOTK",
      "/placeholder.svg?height=300&width=300&text=Zelda+TOTK",
    ],
  },
  {
    id: "software-14",
    title: "Notion Premium",
    description: "All-in-one workspace for notes, tasks, wikis, and databases.",
    image: "/placeholder.svg?height=300&width=300&text=Notion",
    price: 96.0,
    discount: 15,
    platform: "Cross-platform",
    category: "software",
    publisher: "Notion Labs",
    releaseDate: "2022-12-01",
    genres: ["Productivity", "Organization"],
    rating: 4.8,
    sales: 5000000,
    features: ["Collaborative", "Customizable", "All-in-One"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Notion",
      "/placeholder.svg?height=300&width=300&text=Notion",
      "/placeholder.svg?height=300&width=300&text=Notion",
      "/placeholder.svg?height=300&width=300&text=Notion",
    ],
  },
  {
    id: "software-15",
    title: "Figma Professional",
    description: "Collaborative interface design tool for teams.",
    image: "/placeholder.svg?height=300&width=300&text=Figma",
    price: 144.0,
    discount: 10,
    platform: "Cross-platform",
    category: "software",
    publisher: "Figma, Inc.",
    releaseDate: "2022-10-15",
    genres: ["Design", "UI/UX", "Collaboration"],
    rating: 4.9,
    sales: 3000000,
    features: ["Real-time Collaboration", "Prototyping", "Design Systems"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Figma",
      "/placeholder.svg?height=300&width=300&text=Figma",
      "/placeholder.svg?height=300&width=300&text=Figma",
      "/placeholder.svg?height=300&width=300&text=Figma",
    ],
  },
  {
    id: "digital-13",
    title: "Hulu (No Ads) 12 Months",
    description: "Stream thousands of shows and movies without ad interruptions.",
    image: "/placeholder.svg?height=300&width=300&text=Hulu",
    price: 143.88,
    discount: 20,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Hulu",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Streaming Service"],
    rating: 4.5,
    sales: 7000000,
    features: ["Ad-Free", "Original Content", "TV Shows & Movies"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Hulu",
      "/placeholder.svg?height=300&width=300&text=Hulu",
      "/placeholder.svg?height=300&width=300&text=Hulu",
      "/placeholder.svg?height=300&width=300&text=Hulu",
    ],
  },
  {
    id: "digital-14",
    title: "Canva Pro (12 Months)",
    description: "Create professional designs with premium features and content.",
    image: "/placeholder.svg?height=300&width=300&text=Canva+Pro",
    price: 119.99,
    discount: 25,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Canva",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Design"],
    rating: 4.7,
    sales: 10000000,
    features: ["Premium Templates", "Brand Kit", "Background Remover"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Canva+Pro",
      "/placeholder.svg?height=300&width=300&text=Canva+Pro",
      "/placeholder.svg?height=300&width=300&text=Canva+Pro",
      "/placeholder.svg?height=300&width=300&text=Canva+Pro",
    ],
  },
  {
    id: "digital-15",
    title: "Grammarly Premium (12 Months)",
    description: "Advanced writing assistance for clear, mistake-free writing.",
    image: "/placeholder.svg?height=300&width=300&text=Grammarly",
    price: 144.0,
    discount: 20,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Grammarly, Inc.",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Writing Tool"],
    rating: 4.6,
    sales: 8000000,
    features: ["Grammar Checker", "Tone Adjustments", "Plagiarism Detection"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Grammarly",
      "/placeholder.svg?height=300&width=300&text=Grammarly",
      "/placeholder.svg?height=300&width=300&text=Grammarly",
      "/placeholder.svg?height=300&width=300&text=Grammarly",
    ],
  },
]

// Mock publisher data
export const mockPublishers = [
  {
    id: "publisher-1",
    name: "Electronic Arts",
    logo: "/placeholder.svg?height=200&width=200&text=EA",
    description:
      "Electronic Arts Inc. is an American video game company headquartered in Redwood City, California. It is the second-largest gaming company in the Americas and Europe by revenue and market capitalization after Activision Blizzard and ahead of Take-Two Interactive, CD Projekt, and Ubisoft as of May 2020.",
    founded: "1982",
    headquarters: "Redwood City, California, USA",
    website: "https://www.ea.com",
    products: ["FIFA", "Battlefield", "The Sims", "Apex Legends", "Mass Effect"],
    featuredProducts: [
      {
        id: "game-4",
        title: "FIFA 23",
        image: "/placeholder.svg?height=300&width=300&text=FIFA+23",
        discount: 35,
      },
      {
        id: "game-6",
        title: "Battlefield 2042",
        image: "/images/battlefield2042.jpg",
        discount: 60,
      },
      {
        id: "game-9",
        title: "The Sims 4",
        image: "/placeholder.svg?height=300&width=300&text=Sims+4",
        discount: 75,
      },
    ],
  },
  {
    id: "publisher-2",
    name: "Microsoft",
    logo: "/placeholder.svg?height=200&width=200&text=Microsoft",
    description:
      "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
    founded: "1975",
    headquarters: "Redmond, Washington, USA",
    website: "https://www.microsoft.com",
    products: ["Windows", "Office", "Xbox", "Surface", "Azure"],
    featuredProducts: [
      {
        id: "software-1",
        title: "Microsoft Office 2023",
        image: "/images/microsoftoffice.png",
        discount: 20,
      },
      {
        id: "software-3",
        title: "Windows 11 Pro",
        image: "/placeholder.svg?height=300&width=300&text=Windows+11",
        discount: 10,
      },
      {
        id: "digital-2",
        title: "Xbox Game Pass Ultimate (3 Months)",
        image: "/placeholder.svg?height=300&width=300&text=Game+Pass",
        discount: 30,
      },
    ],
  },
  {
    id: "publisher-3",
    name: "CD Projekt RED",
    logo: "/placeholder.svg?height=200&width=200&text=CDPR",
    description:
      "CD Projekt S.A. is a Polish video game developer, publisher and distributor based in Warsaw, founded in May 1994 by Marcin Iwiński and Michał Kiciński.",
    founded: "1994",
    headquarters: "Warsaw, Poland",
    website: "https://www.cdprojekt.com",
    products: ["The Witcher", "Cyberpunk 2077", "GWENT"],
    featuredProducts: [
      {
        id: "game-2",
        title: "Cyberpunk 2077",
        image: "/images/cyberpunk.png",
        discount: 50,
      },
      {
        id: "game-5",
        title: "The Witcher 3: Wild Hunt",
        image: "/placeholder.svg?height=300&width=300&text=Witcher+3",
        discount: 70,
      },
    ],
  },
  {
    id: "publisher-4",
    name: "Adobe",
    logo: "/images/adobelogo.png",
    description:
      "Adobe Inc. is an American multinational computer software company. It has historically focused upon the creation of multimedia and creativity software products.",
    founded: "1982",
    headquarters: "San Jose, California, USA",
    website: "https://www.adobe.com",
    products: ["Photoshop", "Illustrator", "Premiere Pro", "After Effects", "Acrobat"],
    featuredProducts: [
      {
        id: "software-2",
        title: "Adobe Creative Cloud",
        image: "/images/adobecreativecloud.jpg",
        discount: 15,
      },
    ],
  },
  {
    id: "publisher-5",
    name: "Valve",
    logo: "/placeholder.svg?height=200&width=200&text=Valve",
    description:
      "Valve Corporation is an American video game developer, publisher, and digital distribution company headquartered in Bellevue, Washington.",
    founded: "1996",
    headquarters: "Bellevue, Washington, USA",
    products: ["Half-Life", "Counter-Strike", "Portal", "Dota 2", "Steam"],
    featuredProducts: [
      {
        id: "digital-1",
        title: "Steam Wallet $50",
        image: "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
        discount: 5,
      },
    ],
  },
  {
    id: "publisher-6",
    name: "Sony Interactive Entertainment",
    logo: "/placeholder.svg?height=200&width=200&text=Sony",
    description:
      "Sony Interactive Entertainment is a multinational video game and digital entertainment company owned by Sony Group Corporation.",
    founded: "1993",
    headquarters: "San Mateo, California, USA",
    website: "https://www.sie.com",
    products: ["PlayStation", "God of War", "Horizon", "The Last of Us", "Uncharted"],
    featuredProducts: [
      {
        id: "game-11",
        title: "God of War Ragnarök",
        image: "/placeholder.svg?height=300&width=300&text=God+of+War",
        discount: 15,
      },
      {
        id: "game-12",
        title: "Horizon Forbidden West",
        image: "/placeholder.svg?height=300&width=300&text=Horizon",
        discount: 25,
      },
      {
        id: "digital-3",
        title: "PlayStation Plus (12 Months)",
        image: "/placeholder.svg?height=300&width=300&text=PS+Plus",
        discount: 20,
      },
    ],
  },
  {
    id: "publisher-7",
    name: "Square Enix",
    logo: "/placeholder.svg?height=200&width=200&text=Square+Enix",
    description:
      "Square Enix Holdings Co., Ltd. is a Japanese entertainment conglomerate and video game company best known for its Final Fantasy, Dragon Quest, and Kingdom Hearts franchises.",
    founded: "2003",
    headquarters: "Tokyo, Japan",
    website: "https://www.square-enix.com",
    products: ["Final Fantasy", "Dragon Quest", "Kingdom Hearts", "Tomb Raider", "Nier"],
    featuredProducts: [
      {
        id: "game-15",
        title: "Final Fantasy XVI",
        image: "/placeholder.svg?height=300&width=300&text=FF+XVI",
        discount: 0,
      },
    ],
  },
  {
    id: "publisher-8",
    name: "Capcom",
    logo: "/capcomlogo.png",
    description:
      "Capcom Co., Ltd. is a Japanese video game developer and publisher known for creating numerous multi-million selling game franchises.",
    founded: "1979",
    headquarters: "Osaka, Japan",
    website: "https://www.capcom.com",
    products: ["Resident Evil", "Monster Hunter", "Street Fighter", "Devil May Cry", "Mega Man"],
    featuredProducts: [
      {
        id: "game-14",
        title: "Resident Evil Village",
        image: "/capcomlogo.png",
        discount: 40,
      },
    ],
  },
  {
    id: "publisher-9",
    name: "Bandai Namco",
    logo: "/bandainamco.png",
    description:
      "Bandai Namco Entertainment Inc. is a Japanese multinational video game publisher and developer, and the video game arm of Bandai Namco Holdings.",
    founded: "2006",
    headquarters: "Tokyo, Japan",
    website: "https://www.bandainamco.com",
    products: ["Elden Ring", "Dark Souls", "Tekken", "Pac-Man", "Dragon Ball"],
    featuredProducts: [
      {
        id: "game-1",
        title: "Elden Ring",
        image: "/images/elden.png",
        discount: 25,
      },
    ],
  },
]

// Mock user data
export const mockUsers = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=JD",
    password: "password123", // In a real app, this would be properly hashed
    wishlist: ["game-1", "software-2", "digital-3"],
    cart: ["game-4", "software-1"],
    orders: [
      {
        id: "order-1",
        date: "2023-03-15",
        total: 59.99,
        status: "completed",
        items: [
          {
            id: "game-5",
            title: "The Witcher 3: Wild Hunt",
            price: 39.99,
            discount: 70,
            platform: "Steam",
          },
        ],
      },
      {
        id: "order-2",
        date: "2023-02-28",
        total: 149.99,
        status: "completed",
        items: [
          {
            id: "software-1",
            title: "Microsoft Office 2023",
            price: 149.99,
            discount: 20,
            platform: "Windows",
          },
        ],
      },
    ],
    settings: {
      notifications: true,
      newsletter: false,
      darkMode: false,
    },
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=JS",
    password: "password123", // In a real app, this would be properly hashed
    wishlist: ["game-2", "game-11", "digital-7"],
    cart: [],
    orders: [
      {
        id: "order-3",
        date: "2023-04-10",
        total: 89.99,
        status: "completed",
        items: [
          {
            id: "game-11",
            title: "God of War Ragnarök",
            price: 69.99,
            discount: 15,
            platform: "PlayStation",
          },
        ],
      },
    ],
    settings: {
      notifications: true,
      newsletter: true,
      darkMode: true,
    },
  },
]
